name: GitHub Actions

env:
  NODE_VERSION: 16
  SENTRY_URL: https://sentry.io/
  SENTRY_ORG: org
  SENTRY_AUTH_TOKEN: SECRET
  SENTRY_PROJECT: projectName

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]

jobs:
  install:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ env.NODE_VERSION }}.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}.x
      - name: Install modules
        run: npm install
  test:
    name: Test
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: npm run build