name: GitHub Actions

env:
  SENTRY_URL: https://sentry.io/
  SENTRY_ORG: org
  SENTRY_PROJECT: chat
  SENTRY_AUTH_TOKEN: SECRET
  SENTRY_PROJECT: projectName

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: lint code
        run: npm run lint
      - name: test code
        run: npm run test
      - name: build project
        run: npm run build
