name: Push workflows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]

concurrency:
  group: ci-workflows-${{ github.ref }}-1
  cancel-in-progress: true

env:
  NODE_VERSION: 16
  SENTRY_URL: https://sentry.io/
  SENTRY_ORG: org
  SENTRY_AUTH_TOKEN: SECRET
  SENTRY_PROJECT: projectName

jobs:
  call-lint:
    uses: volodyakorol/chat-app/.github/workflows/_lint.yml@main

  call-test:
    needs: call-lint
    uses: volodyakorol/chat-app/.github/workflows/_test.yml@main

  call-build:
    needs: call-test
    uses: volodyakorol/chat-app/.github/workflows/_build.yml@main


  # call-upload-artifact:
  #   needs: call-unit-tests
  #   uses: vonage/vivid-3/.github/workflows/_upload-artifact.yml@main

  # call-pre-release:
  #   needs: call-upload-artifact
  #   uses: vonage/vivid-3/.github/workflows/_publish-package.yml@main
  #   with:
  #     version: 3.0.0