name: GitHub Actions

env:
  NODE_VERSION: 16
  SENTRY_URL: https://sentry.io/
  SENTRY_ORG: org
  SENTRY_AUTH_TOKEN: SECRET
  SENTRY_PROJECT: projectName

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]

permissions:
  contents: read

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}.x
          cache: 'npm'

      - name: Cache NPM dependencies # (2)
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies # (3)
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm ci

  test:
    name: Test
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build project
        run: npm run build